nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /opt:/opt
      - /vagrant/sites:/vagrant/sites
      - /vagrant/conf/frontend-reverse-proxy-nginx/nginx.conf:/etc/nginx/nginx.conf
      - /vagrant/conf/sites-enabled:/etc/nginx/sites-enabled
php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
    volumes:
      - /opt:/opt
      - /vagrant:/vagrant

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - /opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
